### ISSUE TITLE
``list`` in C++/C backend

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#1077]
I was working on #210 and saw some test failures in CPP backend because of the List being not supported in CPP codegen. I can try adding their support and wanted to discuss one of the possibilities. 
1. We can directly use CPP's `std::vector`, which provides almost all the operations as CPython's list like insert, remove, accessing element at any position, etc.

Any other suggestions for the same?
@certik @czgdp1807

**Comment by czgdp1807** [comment]
`std::vector` is slow. I would say going along the same path of LLVM would be better.

**Comment by czgdp1807** [comment]
I am self-assigning this. Here's how I will do it,

1. Generate C/C++ code for lists only if lists are actually used (i.e., present in the ASR).
2. There are two ways to generate C/C++ code for lists,

i. Follow the LLVM logic which keeps everything inlined. Like when you call append in LLVM then the code is generated at that spot and no function call is made to fulfil the purpose. The benefit of this approach is that we don't depend on C/C++ compiler to inline code for us, we are already doing it. The downside is that folks who want to re-use our generated C/C++ code won't be able to edit that easily, because everything is inlined.
ii. If a list is present then generate a struct and all the utility functions for lists associated with it. And just call those functions where-ever `ListAppend`, `ListRemove`, etc nodes are present. The benefit is that users will be able to edit our generated C/C++ code because we provide re-usable implementation of list. The downside is that we depend on C/C++ compiler to inline our code for lists.

IMO, approach ii should be good enough as it provides the option of re-usability. If the user want higher performance then they can go for LLVM backend directly. In addition in future if user provides `--fast` flag with `--show-c` flag then we can implement approach i as well. What do you say @certik ?

**Comment by ArpanShah2k** [comment]
I am interested in fixing this issue . It will be a great opportunity if you allot me to solve this issue . @czgdp1807 @Smit-create @certik @rebcabin @HaoZeke

**Comment by czgdp1807** [comment]
@ArpanShah2k I am already working on this in #1095. Thanks for your interest though. Please let us know if you are interested in any other issue.

**Comment by certik** [comment]
@ArpanShah2k you don't need to ask for permissions, simply pick an issue and implement it, open a PR and go from there. It's very unlikely that somebody works on exactly the same thing at the same time (hour or minute), and in the very unlikely even that somebody does, it's easy to simply join forces and merge the PRs.
