### ISSUE TITLE
Supporting `Const[...]` annotated variables

### ISSUE THREAD

**Issue by czgdp1807** [lcompilers/lpython#1175]
As the title says some syntax examples,

1. `x: Const[i32]` is a constant 32 bit integer variable.
2. `x: Const[CPtr]` is constant C pointer (`void*`) variable.

Any such variable declared in global scope should become macros in C backend. For example, `x: Const[i32] = 0` should become `#define x 0` in C backend.

Posting the link to Zulip chat discussion on the same topic - https://lfortran.zulipchat.com/#narrow/stream/311866-LPython/topic/Constant.20Variables

**Comment by czgdp1807** [comment]
I posted the link to Zulip chat discussion on this topic in the issue description. See, https://lfortran.zulipchat.com/#narrow/stream/311866-LPython/topic/Constant.20Variables.

Coming on to the idea of scanning and producing `foo_h.py`, I think that's fine. Though one concern is `FOO` is still a variable which can be overwritten by the user. Quoting from Zulip chat,

> I see, excellent point. We could do the convention UPPER_CASE = 1, but I think it would fail for codes that happen to have uppercase variables, such as N = 4, which is not meant to be constant. I think using Constant[i32] is probably the way to go. @Gagandeep Singh what do you think?

As @certik said, `Final[i32]` is also an option and its a part of an accepted PEP, see, https://peps.python.org/pep-0591/

**Comment by rebcabin** [comment]
The case for pseudofunctions is more complex. They need to handle closed-over (e.g., global) variables and variables that are modified by side-effect. For example, 

```c
// In pseudofuncs.h
#define idx(i,j) ((j)*n+(i))  // like an expression
#define swap(x,y) { x = x^y; y = x^y; x = x^y; }
```

might become

```python
# in pseudofuncs_h.py --- automatically generated file name

# Types default to i32, OR, are specified in by a YAML file,
# pseudofuncs_h.yaml, written by hand.
def idx(i: i32, j: i32) -> i32
    global n  # found by "occurs" analysis on parameter list
    result = j * n  +  i  # set watchpoint here!
    return result

# Pseudofunctions that operate by side-effect must be guided
# by hand-written YAML that declares, for example, that x and y
# are not parameters and not local variables. The following
# works only on x and y. That's sometimes acceptable.
def swap_x_y() -> None
    global x, y
    x = x ^ y
    y = x ^ y
    x = x ^ y
    return None  # set breakpoint here!
```

For cases where hard-coded targets of side-effects are not acceptable, we can generate some Python code that hacks the Python AST. This is straightforward but involved. We can special-case it for the labs in course101, or we can design a more general solution if it turns out to be a pervasive problem.

The examples above can be accessed in user code as follows:

```python
from pseudofuncs_h import idx, swap_x_y

n: i32 = 42
some_func(idx(6, 19))
x: i32 = 6
y: i32 = 7
print({"before swap": None, "x": x, "y": y})
swap_x_y()
print({"after swap": None, "x": x, "y": y})
```

**Comment by certik** [comment]
Regarding constants, the Final in Python means more than just constant:

> The `typing.Final` type qualifier is used to indicate that a variable or attribute should not be reassigned, redefined, or overridden.

However, the feature that we need is just `Const`: the variable is constant, so you can access it in read-only mode, but you cannot write to it (or if it is an instance of a class, you cannot modify the instance). So `Const` is a subset of `Final`. For this reason I would use `Const` and implement strictly just read-only behavior. We can worry about `Final` later.

**Comment by rebcabin** [comment]
> Regarding constants, the Final in Python means more than just constant:
> 
> > The `typing.Final` type qualifier is used to indicate that a variable or attribute should not be reassigned, redefined, or overridden.
> 
> However, the feature that we need is just `Const`: the variable is constant, so you can access it in read-only mode, but you cannot write to it (or if it is an instance of a class, you cannot modify the instance). So `Const` is a subset of `Final`. For this reason I would use `Const` and implement strictly just read-only behavior. We can worry about `Final` later.

Isn't `Const` an extension of Python? Will CPython be able to interpret `Const`? Are we falling down the slippery slope of extending Python?

**Comment by certik** [comment]
> Isn't Const an extension of Python?

Not any more than `i32` is an extension of Python, since Python only has `int` (arbitrary precision).

> Will CPython be able to interpret Const? 

Yes. Just like it is able to interpret `i32`. It will not check for you that you are not assigning a string to `i32` (you have to use LPython for that), and in the same way it will not check that you are not modifying a `Const` variable (but LPython will).

The contract is that if the code compiles and runs with LPython, it will work exactly the same with CPython.

> Are we falling down the slippery slope of extending Python?

I don't think so.
