### ISSUE TITLE
usability: `int` should default to `i32`

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1926]
The following compiles:

```python
@dataclass
class StringIO:
    _buf     : str
    _0cursor : i32 = i32(0)
    _len     : i32 = i32(0)

if __name__ == '__main__':
    integer_asr : str = '(Integer 4 [])'
    test_dude   : StringIO = StringIO(integer_asr, 0, 15)
    assert test_dude._buf == integer_asr
    assert test_dude._len == 15
```

but, for usability, it should be

```python
@dataclass
class StringIO:
    _buf     : str
    _0cursor : int = 0
    _len     : int = 0

if __name__ == '__main__':
    integer_asr : str = '(Integer 4 [])'
    test_dude   : StringIO = StringIO(integer_asr, 0, 15)
    assert test_dude._buf == integer_asr
    assert test_dude._len == 15
```

**Comment by rebcabin** [comment]
notice `15` did not have to be `i32(15)` -- could it be that `i32` is required (unnecessarily) only in the default-value initializers in the dataclass `StringIO`?

**Comment by certik** [comment]
I am not quite sure. But indeed the default integer should just be i32, no matter where it is used.

**Comment by Shaikh-Ubaid** [comment]
Currently we support `int()` (CPython builtin method) which converts to `i64` and `float()` ((CPython builtin method)) which converts to `f64`. I think we do not yet support `int` and `float` as types.

**Comment by Shaikh-Ubaid** [comment]
In this issue, do we wish to support type alias `int` and `float`? Should `int` correspond to `i32` or `i64`? Should `float` correspond to `f64`?

**Comment by Thirumalai-Shaktivel** [comment]
I think,
- `int` -> `i32`
- `float` -> `f32`
- `double` -> `f64`

Or we can also implement this as https://github.com/lcompilers/lpython/issues/1199

**Comment by certik** [comment]
CPython doesn't have double, and `float` is `f64`, so we can make an alias `float` -> `f64`. Regarding `int`, we have the following options:

* `i32`, as the default int in LPython
* `i64` the widest int currently available
* arbitrary precision integer (not currently implemented, but on our long term todo list, we need it for symbolics and in general it's good to have, since CPython has it, and sometimes it would be useful in Fortran also): the advantage is that `int` would then behave exactly as in CPython, and then `i64`, `i32`, etc. are faster fixed size integers.

So maybe for now we can give a nice error message for `int` that it is not supported yet. And later once we can do arbitrary precision int, we can revisit this.

**Comment by certik** [comment]
Right now let's do:

> So maybe for now we can give a nice error message for int that it is not supported yet.

**Comment by NishantBansal2003** [comment]
Can I work on this issue??

**Comment by NishantBansal2003** [comment]
I have explicitly changed the error message for 'int' to :
```plaintext
Semantic Error: 'int' type is not supported yet.
```

**Comment by certik** [comment]
Just submit a PR, no need to ask for a permission.
