### ISSUE TITLE
Refactoring library routines to their own file does not work 

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1942]
repro : https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/lpython/Issue1942

This works in ordinary CPython.

The second error message seems to be completely bogus.

```bash
└─(14:39:59 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer.py && ./lasr_lexer.out                                           ──(Sun,Jun18)─┘
warning: The module 'lasr_stringio' located in ./lasr_stringio.py cannot be loaded
 --> lasr_lexer.py:9:1
  |
9 | from lasr_stringio import StringIO, read, tell, seek, SEEK_SET, __post_init__
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ imported here

semantic error: Function 'stringio_test' is not declared
   --> ./lasr_stringio.py:109:5
    |
109 |     stringio_test(fd, integer_asr)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

**Comment by Thirumalai-Shaktivel** [comment]
Can you please explain more about the issue?

My understanding about the error message is that:
https://github.com/rebcabin/lpython/blob/3f640450a42ba05d2d69a79f6c3cf41cf4fcf778/lasr/lpython/Issue1942/lasr_lexer.py#L9
The module failed to import because there is some issue with the `lasr_stringio.py` file.

Reason:
While importing the module (`lasr_stringio` in your case), we import all the global statements as well.
So the following if statement is also imported: https://github.com/rebcabin/lpython/blob/3f640450a42ba05d2d69a79f6c3cf41cf4fcf778/lasr/lpython/Issue1942/lasr_stringio.py#L105-L109
Inside the if statement, the compiler is unable to find `stringio_test(...)` symbol in the module scope.
i.e., the function here seems to be commented out: https://github.com/rebcabin/lpython/blob/3f640450a42ba05d2d69a79f6c3cf41cf4fcf778/lasr/lpython/Issue1942/lasr_stringio.py#L86. So, the error.

Either commenting out the if statement or uncommenting the function seems to fix the issue.

**Comment by rebcabin** [comment]
I'll try it again :)

**Comment by rebcabin** [comment]
Done! Thank you !
