### ISSUE TITLE
list.pop segmentation fault

### ISSUE THREAD

**Issue by davidbrochart** [lcompilers/lpython#2215]
The following code segfaults:
```py
from lpython import i32

a: list[i32] = []
i: i32
for i in range(10):
    a.append(1)
    a.pop()
```
Commenting out `a.pop()` doesn't segfaults, or even replacing it with `print(a.pop())`.

**Comment by Thirumalai-Shaktivel** [comment]
Thanks @davidbrochart for trying out LPython!
The problem is, `a.pop()` is treated as an expression (as it returns a value .ie., the popped element). We haven't handled the expression to be treated as a statement yet. As you can see `print(a.pop())` or Assignment statement `x = a.pop()` would work.
We will fix this soon. Thank you.

**Comment by Thirumalai-Shaktivel** [comment]
Thanks @davidbrochart for trying out LPython!
The issue seemed to be fixed! Here is the current output:
```py
from lpython import i32

a: list[i32] = []
i: i32
for i in range(10):
    a.append(1)
    if i > 5:
        a.pop()

print(a)
```
Output
```console
$ lpython examples/expr2.py
[1, 1, 1, 1, 1, 1]
```
You can try out other programs. If you face any issues, please tell us know!
Thank you!

**Comment by davidbrochart** [comment]
Awesome, keep up the great work! LPython rocks :rocket:

**Comment by certik** [comment]
Thank you @davidbrochart for trying LPython and thank you for the excellent bug report. As you can see, it was fixed in 1h. Good bug reports we can fix quickly. :)
