### ISSUE TITLE
Issue with creating autogenerated files

### ISSUE THREAD

**Issue by akshanshbhatt** [lcompilers/lpython#243]
According to the project's README file, running the `./build0.sh` command should 'create autogenerated files' (after successfully following everything mentioned before). However, I am getting this error message on my system. 

```
➜ ./build0.sh                                       
+ ci/version.sh
++ git describe --tags --dirty
+ version=v0.1.0-798-g170235c6a
+ version=0.1.0-798-g170235c6a
+ echo 0.1.0-798-g170235c6a
+ python grammar/asdl_cpp.py
Assuming default values of AST.asdl and ast.h
+ python grammar/asdl_py.py
Assuming default values of Python.asdl and python_ast.py
+ python grammar/asdl_cpp.py grammar/Python.asdl src/lpython/python_ast.h
+ python grammar/asdl_cpp.py grammar/ASR.asdl src/libasr/asr.h
+ cd src/lpython/parser
+ re2c -W -b tokenizer.re -o tokenizer.cpp
+ cd src/lpython/parser
+ re2c -W -b preprocessor.re -o preprocessor.cpp
+ cd src/lpython/parser
+ bison -Wall -d -r all parser.yy
/Library/Developer/CommandLineTools/usr/bin/bison: invalid option -- W
Try `/Library/Developer/CommandLineTools/usr/bin/bison --help' for more information.
```

On some inspection, I found a default bison installation (a much older version) on my system for internal system stuff (macOS 12 arm64), which was causing this issue.

```
➜ bison --version
bison (GNU Bison) 2.3
```

Even though my conda env has bison v3.4 binary installed, the system is not able to recognize it while running the `bison -Wall -d -r all parser.yy` command in the execution of `./build0.sh`.

What am I doing wrong?

**Comment by certik** [comment]
I've seen this error from within VSCode, when the `conda activate lp` command appends (instead of prepends) the path, and so the terminal is using system `bison`, in your case in `/Library/Developer/CommandLineTools/usr/bin/bison`, instead of the Conda's bison, in my case in `/Users/ondrej/mambaforge/envs/lp/bin/bison`. To fix it, I execute:
```bash
export PATH="/Users/ondrej/mambaforge/envs/lp/bin:$PATH"
```
from within VSCode. You should adjust the path for Conda installation.

In a regular terminal on macOS, Conda should just work and you shouldn't need the above workaround.

**Comment by akshanshbhatt** [comment]
I ran the command in the native terminal app and it worked flawlessly.
Thanks!
