### ISSUE TITLE
Optimising C generated code

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#556]
I was looking at the C backend code and found one way to optimize the generated code (not sure if that is true). At present we just include all the headers at the top of the file without actually verifying if they are used or not. Some compilers may warn about unused includes. Should we enable this verifying of includes?

**Comment by certik** [comment]
We can keep track of what features are used, and "enable" the header include as needed.

**Comment by czgdp1807** [comment]
I think we can close this. Optimisation of code is not a concern since we do machine independent optimisations via ASR to ASR passes. We can call those passes in the below function,

https://github.com/lcompilers/lpython/blob/70fef49dbbb6cbb0447f7013231171e5c8b8e5df/src/libasr/codegen/asr_to_c.cpp#L377-L391

See the LLVM code generation for example (we call optimisation passes before starting the visitor),

https://github.com/lcompilers/lpython/blob/70fef49dbbb6cbb0447f7013231171e5c8b8e5df/src/libasr/codegen/asr_to_llvm.cpp#L4924-L4990

**Comment by certik** [comment]
Yes, we'll be able to do all high level optimizations in ASR. ASR is platform independent. The optimizations that are left for the ASR->LLVM or ASR->C backends to do are low level, such as promoting variables to registers, or vectorizing loops. Both LLVM and C compilers can do these. There might be some "collaboration" between ASR optimizations and LLVM / C optimizations for vectorization, such as vectorizing the outer loop, but it might be enough to just do the operation in ASR and just lower. So the ASR->something phase might not need any optimizations on its own.
