### ISSUE TITLE
Add Structs Array support

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#691]
Python code:
```py
from ltypes import i32, f32, dataclass

@dataclass
class A:
    y: f32
    x: i32

def g():
    y: A[2]
    y[0].x = 1
    y[0].y = 1.1
    y[1].x = 2
    y[1].y = 2.2

g()
```
Error:
```
semantic error: Only Name is supported for now in Attribute
  --> expr.py:10:5
   |
10 |     y[0].x = 1
   |     ^^^^^^ 
```

**Comment by redbopo** [comment]
Hi @Smit-create , I think I can fix this with a patch.

**Comment by Smit-create** [comment]
Sure, that would be great. Thank you!

**Comment by redbopo** [comment]
Just the same in previous

```
from ltypes import i32, f32, dataclass

@dataclass
class A:
    y: f32
    x: i32

def g():
    y: A[2]
    y[0].x = 1
    y[0].y = 1.1
    y[1].x = 2
    y[1].y = 2.2

g()
```

**Comment by czgdp1807** [comment]
@redbopo In response to https://github.com/lcompilers/lpython/issues/691#issuecomment-1168675985,

https://github.com/lcompilers/lpython/pull/718/commits/772eda6df1fbf11df7e05eabefc705fcfc12584c

Since we are supporting arrays of structs for the first time, `ArrayRef` visitor is required to set `der_type_name`. In the above commit I have done the same.
