### ISSUE TITLE
DoLoops not working for i64 increment variable

### ISSUE THREAD

**Issue by Madhav2310** [lcompilers/lpython#770]
For the following code: 
```
    i: i64
    for i in range(len(s)):
        char = s[i]
        if ord(char) >= 65 and ord(char) <=90 :
            result += chr(ord(char) + 32)
        else :
            result += char
```
This works for `i: i32` but not for `i: i64`

**Comment by namannimmo10** [comment]
Thanks for the report! It seems to me that the issue is caused here:

https://github.com/lcompilers/lpython/blob/1c7430f7814ca7cb171ead0fec5ef103cca01c93/src/lpython/semantics/python_ast_to_asr.cpp#L2681-L2682

If let's say we change the kind from `4` to `8`, then it works for `i64` but not for `i32`. Looks like an easy fix, we should replace `4` with the kind of `i` (variable).
